backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

  # These lines should *not* be indented
media_folder: "public/assets/blog" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
   - name: "blog" # Used in routes, e.g., /admin/collections/blog
     label: "Blog" # Used in the UI
     folder: "src/blog" # The path to the folder where the documents are stored
     create: true # Allow users to create new documents in this collection
     slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
     fields: 
           - { label:"Title", name:"title", widget:"string" }
           - { label:"Description", name:"description", widget:"string" }
           - { label:"Author", name:"author", widget:"string" }
           - { label:"Date", name:"date", widget:"datetime" }
           - { label:"Tags", name:"tags", widget:"list", default:["post"] }
           - { label:"Featured image", name:"image", widget:"image" }
           - { label:"Image caption", name:"imageAlt", widget:"string" }
           - { label:"Body", name:"body", widget:"markdown" }
          # The fields for each document, usually in front matter